@url_dev=http://localhost:3052/v1/api

### signup

POST {{url_dev}}/shop/signup
Content-Type: application/json

{
    "name": "Nha hang SAO MAI4",
    "email": "saomairestaurant4@gmail.com",
    "password": "123123"
}